name: "Gracias BeerJS 76"
description: "Action para la BeerJS 76"
author: "Ata Sanchez (@ataschz)"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
